name: build and push an image to a docker hub

on:
  push:
    - branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build ./backend/  -t  erp_test/design-and-development-of-core-modules-for-a-public-transport-erp-system-main-backend:latest
          docker build ./frontend/  -t  erp_test/design-and-development-of-core-modules-for-a-public-transport-erp-system-main-frontend:latest

      - name: push image
        uses: |
          docker login -u youssefbahri -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push  erp_test/design-and-development-of-core-modules-for-a-public-transport-erp-system-main-backend:latest
          docker push  erp_test/design-and-development-of-core-modules-for-a-public-transport-erp-system-main-frontend:latest
